import { DailyReport } from '../types'

export const mockReports: DailyReport[] = [
  {
    id: '1',
    title: 'Dashboard UI Implementation',
    description: 'Started implementing the new dashboard layout with responsive design',
    tasksCompleted: [
      'Designed sidebar navigation',
      'Created responsive grid layout',
      'Implemented dark mode toggle',
    ],
    challenges: ['Responsive design on mobile devices', 'Color scheme consistency'],
    project: 'Dashboard Redesign',
    workDuration: 8,
    images: [],
    authorId: '1',
    authorName: 'John Smith',
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: '2',
    title: 'API Integration for Reports',
    description: 'Integrated backend API endpoints for report creation and retrieval',
    tasksCompleted: [
      'Created API service layer',
      'Implemented error handling',
      'Added request validation',
    ],
    challenges: ['CORS issues resolved', 'Rate limiting implementation'],
    project: 'Reports System',
    workDuration: 6,
    images: [],
    authorId: '1',
    authorName: 'John Smith',
    createdAt: new Date('2024-03-09'),
    updatedAt: new Date('2024-03-09'),
  },
  {
    id: '3',
    title: 'Design System Refinement',
    description: 'Refined design tokens and component library for consistency',
    tasksCompleted: [
      'Updated color palette',
      'Standardized spacing',
      'Created component documentation',
    ],
    challenges: ['Accessibility compliance', 'Browser compatibility'],
    project: 'Design System',
    workDuration: 7,
    images: [],
    authorId: '2',
    authorName: 'Sarah Johnson',
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: '4',
    title: 'Database Schema Design',
    description: 'Designed and reviewed database schema for new features',
    tasksCompleted: [
      'Created entity relationship diagram',
      'Optimized query performance',
      'Set up indexing strategy',
    ],
    challenges: ['Performance optimization', 'Data migration planning'],
    project: 'Backend Infrastructure',
    workDuration: 8,
    images: [],
    authorId: '3',
    authorName: 'Mike Chen',
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: '5',
    title: 'Marketing Campaign Planning',
    description: 'Planned and outlined the Q2 marketing campaign strategy',
    tasksCompleted: [
      'Developed messaging framework',
      'Created timeline and milestones',
      'Identified target audience segments',
    ],
    challenges: ['Budget allocation', 'Team coordination'],
    project: 'Q2 Marketing',
    workDuration: 7,
    images: [],
    authorId: '4',
    authorName: 'Emma Davis',
    createdAt: new Date('2024-03-09'),
    updatedAt: new Date('2024-03-09'),
  },
  {
    id: '6',
    title: 'Performance Optimization',
    description: 'Optimized application performance and reduced load times',
    tasksCompleted: [
      'Implemented code splitting',
      'Optimized images and assets',
      'Improved caching strategy',
    ],
    challenges: ['Third-party script optimization', 'Testing on slow networks'],
    project: 'Dashboard Redesign',
    workDuration: 8,
    images: [],
    authorId: '1',
    authorName: 'John Smith',
    createdAt: new Date('2024-03-08'),
    updatedAt: new Date('2024-03-08'),
  },
  {
    id: '7',
    title: 'Team Collaboration Setup',
    description: 'Set up development environment and collaboration tools',
    tasksCompleted: [
      'Configured Git workflows',
      'Set up CI/CD pipeline',
      'Documented development guidelines',
    ],
    challenges: ['Team adoption', 'Integration complexity'],
    project: 'DevOps Infrastructure',
    workDuration: 6,
    images: [],
    authorId: '3',
    authorName: 'Mike Chen',
    createdAt: new Date('2024-03-07'),
    updatedAt: new Date('2024-03-07'),
  },
  {
    id: '8',
    title: 'Customer Feedback Analysis',
    description: 'Analyzed customer feedback and identified key improvement areas',
    tasksCompleted: [
      'Reviewed support tickets',
      'Conducted user interviews',
      'Created feedback report',
    ],
    challenges: ['Data organization', 'Prioritization'],
    project: 'Customer Insights',
    workDuration: 5,
    images: [],
    authorId: '4',
    authorName: 'Emma Davis',
    createdAt: new Date('2024-03-06'),
    updatedAt: new Date('2024-03-06'),
  },
  {
    id: '9',
    title: 'Testing and QA',
    description: 'Performed comprehensive testing of new features',
    tasksCompleted: [
      'Created test cases',
      'Performed regression testing',
      'Documented bugs and issues',
    ],
    challenges: ['Edge case coverage', 'Automation setup'],
    project: 'Reports System',
    workDuration: 7,
    images: [],
    authorId: '2',
    authorName: 'Sarah Johnson',
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-03-05'),
  },
  {
    id: '10',
    title: 'Documentation Update',
    description: 'Updated technical documentation and user guides',
    tasksCompleted: [
      'Wrote API documentation',
      'Created user tutorials',
      'Updated changelog',
    ],
    challenges: ['Keeping pace with features', 'Clarity for diverse audiences'],
    project: 'Documentation',
    workDuration: 4,
    images: [],
    authorId: '3',
    authorName: 'Mike Chen',
    createdAt: new Date('2024-03-04'),
    updatedAt: new Date('2024-03-04'),
  },
]
