import { User, Report, Analytics } from './types'

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'John Davis',
    email: 'john@company.com',
    role: 'employee',
    department: 'Engineering',
    avatar: 'JD',
  },
  {
    id: 'user-2',
    name: 'Sarah Chen',
    email: 'sarah@company.com',
    role: 'manager',
    department: 'Engineering',
    avatar: 'SC',
  },
  {
    id: 'user-3',
    name: 'Mike Johnson',
    email: 'mike@company.com',
    role: 'employee',
    department: 'Design',
    avatar: 'MJ',
  },
  {
    id: 'user-4',
    name: 'Emma Wilson',
    email: 'emma@company.com',
    role: 'employee',
    department: 'Engineering',
    avatar: 'EW',
  },
  {
    id: 'user-5',
    name: 'Alex Kumar',
    email: 'alex@company.com',
    role: 'manager',
    department: 'Product',
    avatar: 'AK',
  },
]

export const mockReports: Report[] = [
  {
    id: 'report-1',
    employeeId: 'user-1',
    date: '2024-03-10',
    tasks: [
      'Completed API authentication refactor',
      'Code review for pull request #234',
      'Fixed critical bug in dashboard',
    ],
    accomplishments: 'Successfully refactored authentication system, reducing load time by 30%',
    challenges: 'Encountered compatibility issues with legacy system components',
    nextDay: 'Deploy authentication changes to staging and conduct full test suite',
    mood: 'great',
    createdAt: '2024-03-10T17:30:00Z',
    updatedAt: '2024-03-10T17:30:00Z',
  },
  {
    id: 'report-2',
    employeeId: 'user-1',
    date: '2024-03-09',
    tasks: [
      'Started authentication refactor',
      'Updated documentation',
      'Attended team standup',
    ],
    accomplishments: 'Completed initial planning and architecture design for auth system',
    challenges: 'Need clarification on specific requirements for OAuth integration',
    nextDay: 'Begin implementation of OAuth flow',
    mood: 'good',
    createdAt: '2024-03-09T17:45:00Z',
    updatedAt: '2024-03-09T17:45:00Z',
  },
  {
    id: 'report-3',
    employeeId: 'user-3',
    date: '2024-03-10',
    tasks: [
      'Designed new dashboard layout',
      'Created component mockups',
      'Client feedback session',
    ],
    accomplishments: 'Delivered 3 high-fidelity design variations that client approved',
    challenges: 'Managing scope creep in design iterations',
    nextDay: 'Handoff designs to engineering team',
    mood: 'good',
    createdAt: '2024-03-10T18:00:00Z',
    updatedAt: '2024-03-10T18:00:00Z',
  },
  {
    id: 'report-4',
    employeeId: 'user-4',
    date: '2024-03-10',
    tasks: [
      'Database optimization work',
      'Performance testing',
      'Documentation updates',
    ],
    accomplishments: 'Improved query performance by 40% through indexing optimization',
    challenges: 'Need to coordinate with DevOps on deployment strategy',
    nextDay: 'Deploy optimizations to production environment',
    mood: 'great',
    createdAt: '2024-03-10T16:30:00Z',
    updatedAt: '2024-03-10T16:30:00Z',
  },
  {
    id: 'report-5',
    employeeId: 'user-4',
    date: '2024-03-08',
    tasks: [
      'Analyzed performance bottlenecks',
      'Created optimization roadmap',
      'Reviewed database schema',
    ],
    accomplishments: 'Identified 5 critical performance issues for the platform',
    challenges: 'Some issues require infrastructure changes',
    nextDay: 'Start implementation of optimizations',
    mood: 'neutral',
    createdAt: '2024-03-08T17:00:00Z',
    updatedAt: '2024-03-08T17:00:00Z',
  },
  {
    id: 'report-6',
    employeeId: 'user-1',
    date: '2024-03-08',
    tasks: [
      'Reviewed team pull requests',
      'Updated build scripts',
      'Attended architecture meeting',
    ],
    accomplishments: 'Streamlined CI/CD pipeline, reducing build time by 25%',
    challenges: 'Some team members need training on new build process',
    nextDay: 'Schedule training session for the team',
    mood: 'good',
    createdAt: '2024-03-08T18:15:00Z',
    updatedAt: '2024-03-08T18:15:00Z',
  },
]

export const mockAnalytics: Analytics = {
  totalReports: 24,
  reportsThisMonth: 18,
  averageMood: 3.2,
  completionRate: 89,
  reportsTimeline: [
    { date: '2024-03-01', count: 2 },
    { date: '2024-03-02', count: 3 },
    { date: '2024-03-03', count: 1 },
    { date: '2024-03-04', count: 4 },
    { date: '2024-03-05', count: 2 },
    { date: '2024-03-06', count: 3 },
    { date: '2024-03-07', count: 2 },
    { date: '2024-03-08', count: 3 },
    { date: '2024-03-09', count: 2 },
    { date: '2024-03-10', count: 4 },
  ],
  moodDistribution: [
    { mood: 'Great', count: 8 },
    { mood: 'Good', count: 10 },
    { mood: 'Neutral', count: 4 },
    { mood: 'Bad', count: 2 },
  ],
  departmentStats: [
    { department: 'Engineering', reports: 14, average_mood: 3.4 },
    { department: 'Design', reports: 5, average_mood: 3.0 },
    { department: 'Product', reports: 5, average_mood: 3.2 },
  ],
}
